name: CI/CD
on: [push]
jobs:
  Build_and_package:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ls -la
      - name: Build with Maven
      - run: mvn -B package --file pom.xml
