name: CI/CD
on: [push]
jobs:
  Build_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  Set up JDK 17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ls -la
      - name: Build with Maven
        run: mvn -B package --file pom.xml
